### ISSUE TITLE
filter_by() got an unexpected keyword argument 'base'

### ISSUE THREAD

**Issue by y2kenny** [saltstack-formulas/nfs-formula#11] opened 2016-01-28 22:35 UTC
```
   Data failed to compile:
----------
    Rendering SLS "base:nfs.mount" failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 77, in render_tmpl
    output = render_str(tmplstr, context, tmplpath)
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 169, in render_jinja_tmpl
    output = jinja_env.from_string(tmplstr).render(**unicode_context)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 1, in top-level template code
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 1013, in make_module
    return TemplateModule(self, self.new_context(vars, shared, locals))
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 1070, in __init__
    self._body_stream = list(template.root_render_func(context))
  File "/var/cache/salt/minion/files/base/nfs/map.jinja", line 15, in top-level template code
    {% set nfs = salt['grains.filter_by'](map, merge=salt['pillar.get']('nfs:lookup'), base='default') %}
TypeError: filter_by() got an unexpected keyword argument 'base'
```
# salt-master --version

salt-master 2015.8.3 (Beryllium)
# salt '*' test.versions_report

```
           Salt: 0.17.5
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
            ZMQ: 4.0.4
```

**Comment by y2kenny** [comment] 2016-01-29 16:31
Things seems to work after I removed the `, base='default'` in the formula.

**Comment by javierbertoli** [comment] 2018-03-26 20:05
The issue is +2yr old, and `map.jinja` has been refactored. Closing.

**Closed as completed by javierbertoli** 2018-03-26 20:05 UTC
